use ark_std::sync::Arc;
use sonobe_primitives::{
    arithmetizations::Arith,
    commitments::{CommitmentKey, GroupBasedVectorCommitment},
    traits::SonobeField,
};

use crate::{ova::AbstractOva, Error, FoldingSchemeKeyGenerator};

impl<VC: GroupBasedVectorCommitment, TF: SonobeField, const CHALLENGE_BITS: usize>
    FoldingSchemeKeyGenerator for AbstractOva<VC, TF, CHALLENGE_BITS>
{
    fn generate_keys(ck: Self::PublicParam, r1cs: Self::Arith) -> Result<Self::DeciderKey, Error> {
        let ck = Arc::new(ck);
        let r1cs = Arc::new(r1cs);
        if ck.max_scalars_len() < r1cs.n_constraints() + r1cs.n_witnesses() {
            return Err(Error::InvalidPublicParameters(
                "The commitment key generated by preprocessing is too short for the R1CS instance"
                    .into(),
            ));
        }
        Ok(Self::DeciderKey { arith: r1cs, ck })
    }
}
