[workspace]
members = [
    "lib/folding-schemes",
    "lib/solidity-verifiers",
    "cli",
    "lib/experimental-frontends",
    "wip/primitives",
    "wip/fs",
    "wip/ivc",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/privacy-scaling-explorations/sonobe/"

[workspace.dependencies]
askama = { version = "0.12.0", default-features = false }
clap = { version = "4.4" }
clap-verbosity-flag = { version = "2.1" }
criterion = { version = "0.5" }
env_logger = { version = "0.10" }
log = { version = "0.4" }
num-bigint = { version = "0.4.3" }
num-integer = { version = "0.1" }
num-traits = { version = "0.2" }
pprof = { version = "0.13" }
serde = { version = "^1.0.0" }
serde_json = { version = "^1.0.0" }
sha3 = { version = "0.10" }
rayon = { version = "1" }
revm = { version = "29.0.1", default-features = false }
thiserror = { version = "2.0.16" }
wasmer = { version = "6.1.0-rc.3", default-features = false }

# Circuit DSLs
acvm = { git = "https://github.com/noir-lang/noir", rev = "6e469c3", default-features = false }
ark-circom = { git = "https://github.com/arkworks-rs/circom-compat", default-features = false }
noname = { git = "https://github.com/winderica/noname", rev = "a6f41cc", default-features = false }

# Arkworks family
ark-crypto-primitives = { git = "https://github.com/arkworks-rs/crypto-primitives", default-features = false }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-groth16 = { git = "https://github.com/arkworks-rs/groth16", default-features = false }
ark-poly = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-poly-commit = { git = "https://github.com/arkworks-rs/poly-commit", default-features = false }
ark-r1cs-std = { git = "https://github.com/arkworks-rs/r1cs-std", default-features = false }
ark-relations = { git = "https://github.com/arkworks-rs/snark", default-features = false }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-snark = { git = "https://github.com/arkworks-rs/snark", default-features = false }
ark-std = { git = "https://github.com/arkworks-rs/std", default-features = false }

# Ark curves
ark-bn254 = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-grumpkin = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-pallas = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-vesta = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-mnt4-298 = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-mnt6-298 = { git = "https://github.com/arkworks-rs/algebra", default-features = false }

# Local crates
experimental-frontends = { path = "lib/experimental-frontends", default-features = false }
folding-schemes = { path = "lib/folding-schemes", default-features = false }
solidity-verifiers = { path = "lib/solidity-verifiers", default-features = false }

sonobe-primitives = { path = "wip/primitives", default-features = false }
sonobe-fs = { path = "wip/fs", default-features = false }
sonobe-ivc = { path = "wip/ivc", default-features = false }

[patch.crates-io]
# We depend on git versions of arkworks crates, but some of our dependencies
# depend on crates.io versions, so we need to override them here to avoid
# version conflicts.
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-ec = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-std = { git = "https://github.com/arkworks-rs/std" }
ark-crypto-primitives = { git = "https://github.com/winderica/crypto-primitives", rev = "af003fc" }
ark-r1cs-std = { git = "https://github.com/winderica/r1cs-std", rev = "ae8283a" }         # "sw-fix-updated" branch

# Curve crates also need git versions
ark-bls12-381 = { git = "https://github.com/arkworks-rs/algebra" }
ark-bn254 = { git = "https://github.com/arkworks-rs/algebra" }

[patch."https://github.com/arkworks-rs/crypto-primitives"]
ark-crypto-primitives = { git = "https://github.com/winderica/crypto-primitives", rev = "af003fc" }

[patch."https://github.com/arkworks-rs/r1cs-std"]
ark-r1cs-std = { git = "https://github.com/winderica/r1cs-std", rev = "ae8283a" }         # "sw-fix-updated" branch
