// code forked from:
// https://github.com/EspressoSystems/hyperplonk/tree/main/subroutines/src/poly_iop/sum_check
//
// Copyright (c) 2023 Espresso Systems (espressosys.com)
// This file is part of the HyperPlonk library.

// You should have received a copy of the MIT License
// along with the HyperPlonk library. If not, see <https://mit-license.org/>.

//! This module implements the sum check protocol.

use ark_ff::PrimeField;
use ark_poly::{
    univariate::DensePolynomial, DenseMultilinearExtension, DenseUVPolynomial, Polynomial,
};
use ark_std::{cfg_chunks, cfg_into_iter, cfg_iter, fmt::Debug};
#[cfg(feature = "parallel")]
use rayon::prelude::*;
use thiserror::Error;

use crate::transcripts::{Absorbable, Transcript};

use utils::{
    barycentric_weights, compute_lagrange_interpolated_poly, extrapolate, VPAuxInfo,
    VirtualPolynomial,
};

pub mod utils;

#[derive(Debug, Error)]
pub enum Error {
    #[error("Invalid Polynomial IOP Prover: {0}")]
    InvalidPolyIOPProver(String),
    #[error("Invalid Polynomial IOP Verifier: {0}")]
    InvalidPolyIOPVerifier(String),
    #[error("Invalid Polynomial IOP Proof: {0}")]
    InvalidPolyIOPProof(String),
    #[error("Invalid Polynomial IOP Parameters: {0}")]
    InvalidPolyIOPParameters(String),
}

/// An IOP proof is a collections of
/// - messages from prover to verifier at each round through the interactive
///   protocol.
/// - a point that is generated by the transcript for evaluation
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct IOPProof<F> {
    pub point: Vec<F>,
    pub proofs: Vec<Vec<F>>,
}

/// A SumCheckSubClaim is a claim generated by the verifier at the end of
/// verification when it is convinced.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SumCheckSubClaim<F: PrimeField> {
    /// the multi-dimensional point that this multilinear extension is evaluated
    /// to
    pub point: Vec<F>,
    /// the expected evaluation
    pub expected_evaluation: F,
}

#[derive(Clone, Debug, Default, Copy, PartialEq, Eq)]
pub struct IOPSumCheck;

impl IOPSumCheck {
    pub fn prove<F: PrimeField + Absorbable<F>>(
        mut poly: VirtualPolynomial<F>,
        transcript: &mut impl Transcript<F>,
    ) -> Result<(IOPProof<F>, Vec<DenseMultilinearExtension<F>>), Error> {
        transcript.add(&F::from(poly.aux_info.num_variables as u64));
        transcript.add(&F::from(poly.aux_info.max_degree as u64));
        let extrapolation_aux = (1..poly.aux_info.max_degree)
            .map(|degree| {
                let points = (0..1 + degree as u64).map(F::from).collect::<Vec<_>>();
                let weights = barycentric_weights(&points);
                (points, weights)
            })
            .collect::<Vec<_>>();
        let mut prover_msgs = Vec::with_capacity(poly.aux_info.num_variables);
        let mut challenges = Vec::with_capacity(poly.aux_info.num_variables);
        for i in 0..poly.aux_info.num_variables {
            let mut products_sum = vec![F::ZERO; poly.aux_info.max_degree + 1];

            // Step 2: generate sum for the partial evaluated polynomial:
            // f(r_1, ... r_m,, x_{m+1}... x_n)

            poly.products.iter().for_each(|(coefficient, products)| {
                #[cfg(feature = "parallel")]
                let mut sum = cfg_into_iter!(0..1 << (poly.aux_info.num_variables - i - 1))
                    .fold(
                        || {
                            (
                                vec![(F::ZERO, F::ZERO); products.len()],
                                vec![F::ZERO; products.len() + 1],
                            )
                        },
                        |(mut buf, mut acc), b| {
                            buf.iter_mut()
                                .zip(products.iter())
                                .for_each(|((eval, step), f)| {
                                    let table = &poly.flattened_ml_extensions[*f];
                                    *eval = table[b << 1];
                                    *step = table[(b << 1) + 1] - table[b << 1];
                                });
                            acc[0] += buf.iter().map(|(eval, _)| eval).product::<F>();
                            acc[1..].iter_mut().for_each(|acc| {
                                buf.iter_mut().for_each(|(eval, step)| *eval += step);
                                *acc += buf.iter().map(|(eval, _)| eval).product::<F>();
                            });
                            (buf, acc)
                        },
                    )
                    .map(|(_, partial)| partial)
                    .reduce(
                        || vec![F::ZERO; products.len() + 1],
                        |mut sum, partial| {
                            sum.iter_mut()
                                .zip(partial.iter())
                                .for_each(|(sum, partial)| *sum += partial);
                            sum
                        },
                    );
                #[cfg(not(feature = "parallel"))]
                let mut sum = cfg_into_iter!(0..1 << (poly.aux_info.num_variables - i - 1))
                    .fold(
                        (
                            vec![(F::ZERO, F::ZERO); products.len()],
                            vec![F::ZERO; products.len() + 1],
                        ),
                        |(mut buf, mut acc), b| {
                            buf.iter_mut()
                                .zip(products.iter())
                                .for_each(|((eval, step), f)| {
                                    let table = &poly.flattened_ml_extensions[*f];
                                    *eval = table[b << 1];
                                    *step = table[(b << 1) + 1] - table[b << 1];
                                });
                            acc[0] += buf.iter().map(|(eval, _)| eval).product::<F>();
                            acc[1..].iter_mut().for_each(|acc| {
                                buf.iter_mut().for_each(|(eval, step)| *eval += step as &_);
                                *acc += buf.iter().map(|(eval, _)| eval).product::<F>();
                            });
                            (buf, acc)
                        },
                    )
                    .1;
                sum.iter_mut().for_each(|sum| *sum *= coefficient);
                let extraploation = cfg_into_iter!(0..poly.aux_info.max_degree - products.len())
                    .map(|i| {
                        let (points, weights) = &extrapolation_aux[products.len() - 1];
                        let at = F::from((products.len() + 1 + i) as u64);
                        extrapolate(points, weights, &sum, &at)
                    })
                    .collect::<Vec<_>>();
                products_sum
                    .iter_mut()
                    .zip(sum.iter().chain(extraploation.iter()))
                    .for_each(|(products_sum, sum)| *products_sum += sum);
            });

            let mut prover_poly = compute_lagrange_interpolated_poly(&products_sum).coeffs;
            prover_poly.resize(poly.aux_info.max_degree + 1, F::ZERO);
            transcript.add(&prover_poly);
            prover_msgs.push(prover_poly);

            let challenge = transcript.challenge_field_element();
            challenges.push(challenge);
            poly.flattened_ml_extensions.iter_mut().for_each(|mle| {
                mle.evaluations = cfg_chunks!(mle.evaluations, 2)
                    .map(|chunk| chunk[0] + challenge * (chunk[1] - chunk[0]))
                    .collect();
                mle.num_vars -= 1;
            });
        }

        Ok((
            IOPProof {
                point: challenges,
                proofs: prover_msgs,
            },
            poly.flattened_ml_extensions,
        ))
    }

    pub fn verify<F: PrimeField + Absorbable<F>>(
        claimed_sum: F,
        proof: &IOPProof<F>,
        aux_info: &VPAuxInfo,
        transcript: &mut impl Transcript<F>,
    ) -> Result<SumCheckSubClaim<F>, Error> {
        transcript.add(&F::from(aux_info.num_variables as u64));
        transcript.add(&F::from(aux_info.max_degree as u64));
        assert_eq!(aux_info.num_variables, proof.proofs.len());

        let challenges = proof
            .proofs
            .iter()
            .map(|msg| {
                transcript.add(msg);
                transcript.challenge_field_element()
            })
            .collect::<Vec<_>>();

        // the deferred check during the interactive phase:
        // 2. set `expected` to P(r)`
        let mut expected_vec = cfg_iter!(proof.proofs)
            .zip(&challenges)
            .map(|(coeffs, challenge)| {
                DensePolynomial::from_coefficients_slice(coeffs).evaluate(challenge)
            })
            .collect::<Vec<_>>();

        // insert the asserted_sum to the first position of the expected vector
        expected_vec.insert(0, claimed_sum);

        for (coeffs, &expected) in proof.proofs.iter().zip(expected_vec.iter()) {
            let eval_at_one: F = coeffs.iter().sum();
            let eval_at_zero: F = if coeffs.is_empty() {
                F::zero()
            } else {
                coeffs[0]
            };

            // the deferred check during the interactive phase:
            // 1. check if the received 'P(0) + P(1) = expected`.
            if eval_at_one + eval_at_zero != expected {
                return Err(Error::InvalidPolyIOPProof(
                    "Prover message is not consistent with the claim.".to_string(),
                ));
            }
        }
        Ok(SumCheckSubClaim {
            point: challenges,
            // the last expected value (not checked within this function) will be included in the
            // subclaim
            expected_evaluation: expected_vec[expected_vec.len() - 1],
        })
    }
}

#[cfg(test)]
pub mod tests {
    use ark_crypto_primitives::sponge::{poseidon::PoseidonSponge, CryptographicSponge};
    use ark_ff::Field;
    use ark_pallas::Fr;
    use ark_poly::{DenseMultilinearExtension, MultilinearExtension};
    use ark_std::{test_rng, One, Zero};

    use crate::transcripts::poseidon::poseidon_canonical_config;

    use super::*;

    #[test]
    pub fn sumcheck_poseidon() -> Result<(), Error> {
        let n_vars = 10;

        let mut rng = test_rng();
        let poly_mle = DenseMultilinearExtension::rand(n_vars, &mut rng);
        let virtual_poly = VirtualPolynomial::new_from_mle(poly_mle, Fr::ONE);

        sumcheck_poseidon_opt(virtual_poly)?;

        // test with zero poly
        let poly_mle = DenseMultilinearExtension::from_evaluations_vec(
            n_vars,
            vec![Fr::zero(); 2u32.pow(n_vars as u32) as usize],
        );
        let virtual_poly = VirtualPolynomial::new_from_mle(poly_mle, Fr::ONE);
        sumcheck_poseidon_opt(virtual_poly)?;
        Ok(())
    }

    fn sumcheck_poseidon_opt(virtual_poly: VirtualPolynomial<Fr>) -> Result<(), Error> {
        let aux_info = virtual_poly.aux_info.clone();
        let poseidon_config = poseidon_canonical_config::<Fr>();

        // sum-check prove
        let mut transcript_p: PoseidonSponge<Fr> = PoseidonSponge::<Fr>::new(&poseidon_config);
        let (sum_check, _) = IOPSumCheck::prove(virtual_poly, &mut transcript_p)?;

        // sum-check verify
        let poly = DensePolynomial::from_coefficients_vec(sum_check.proofs[0].clone());
        let claimed_sum = poly.evaluate(&Fr::one()) + poly.evaluate(&Fr::zero());
        let mut transcript_v: PoseidonSponge<Fr> = PoseidonSponge::<Fr>::new(&poseidon_config);
        let res_verify = IOPSumCheck::verify(claimed_sum, &sum_check, &aux_info, &mut transcript_v);

        assert!(res_verify.is_ok());
        Ok(())
    }
}
