[package]
name = "sonobe-snarks"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ark-bn254 = { workspace = true, features = ["curve", "r1cs"], optional = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true, features = ["asm"] }
ark-groth16 = { workspace = true }
ark-poly = { workspace = true }
ark-relations = { workspace = true }
ark-serialize = { workspace = true }
ark-snark = { workspace = true }
ark-std = { workspace = true, features = ["getrandom"] }
askama = { workspace = true, optional = true }
hashbrown = { workspace = true }
itertools = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }

sonobe-primitives = { workspace = true }

[dev-dependencies]
ark-bn254 = { workspace = true, features = ["curve", "r1cs"] }
ark-grumpkin = { workspace = true, features = ["r1cs"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies]
wasm-bindgen-test = { workspace = true }

[features]
default = []
evm = ["dep:askama", "sonobe-primitives/evm", "dep:ark-bn254"]
parallel = [
    "sonobe-primitives/parallel",
    "ark-groth16/parallel",
]
