//! Key generation for Ova.

use ark_std::sync::Arc;
use sonobe_primitives::{
    arithmetizations::{Arith, ArithConfig},
    commitments::{CommitmentKey, GroupBasedCommitment},
    traits::SonobeField,
};

use crate::{Error, FoldingSchemeKeyGenerator, ova::AbstractOva};

impl<CM: GroupBasedCommitment, TF: SonobeField, const CHALLENGE_BITS: usize>
    FoldingSchemeKeyGenerator for AbstractOva<CM, TF, CHALLENGE_BITS>
{
    fn generate_keys(ck: Self::PublicParam, r1cs: Self::Arith) -> Result<Self::DeciderKey, Error> {
        let ck = Arc::new(ck);
        let r1cs = Arc::new(r1cs);
        let cfg = r1cs.config();
        if ck.max_scalars_len() < cfg.n_constraints() + cfg.n_witnesses() {
            return Err(Error::InvalidPublicParameters(
                "The commitment key generated by preprocessing is too short for the R1CS instance"
                    .into(),
            ));
        }
        Ok(Self::DeciderKey { arith: r1cs, ck })
    }
}
